apiVersion: v1
kind: Service
metadata:
  name: products-api
  namespace: products
spec:
  type: ClusterIP
  selector:
    app: products-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
